name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      -
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      -
        name: Build [Devices] with Gradle
        run: cd services/devices-service && gradle build

      -
        name: Build [Devices] and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: services/devices-service
          push: true
          tags: ghcr.io/belkevglaz/devices-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build [Automation] with Gradle
        run: cd services/automation-service && gradle build

      -
        name: Build [Automation] and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: services/automation-service
          push: true
          tags: ghcr.io/belkevglaz/automation-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build [Telemetry] with Gradle
        run: cd services/telemetry-service && gradle build

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: services/telemetry-service
          push: true
          tags: ghcr.io/belkevglaz/telemetry-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
